name: iOS TestFlight Build

on:
  push:
    paths:
      - github/workflows/build.yml  # Change this to the branch you want to trigger the build from

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout codee
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: actions/setup-xcode@v2
        with:
          xcode-version: 14.3.1  # Use the desired Xcode version

      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod install

      - name: Build and archive
        run: |
          xcodebuild clean archive -workspace SampleApp.xcworkspace -scheme SampleApp -archivePath build/SampleApp.xcarchive

      - name: Export archive as IPA
        run: |
          xcodebuild -exportArchive -archivePath build/SampleApp.xcarchive -exportPath build -exportOptionsPlist ExportOptions.plist

      - name: Upload to TestFlight
        run: |
          xcrun altool --upload-app -t ios -f build/SampleApp.ipa -u ${{ secrets.APPSTORE_USERNAME }} -p ${{ secrets.APPSTORE_PASSWORD }}

