name: Build and Deploy IPA

on:

  push:

    paths:

      - .github/workflows/build.yml

 

jobs:

  build:

    runs-on: macos-latest

 

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: List Directory Contents

        run: ls -R

      - name: Build IPA

        run: xcodebuild -workspace SampleApp.xcworkspace -scheme SampleApp -configuration Release clean archive -archivePath SampleApp.xcarchive CODE_SIGNING_ALLOWED=NO

      - name: Export IPA

        run: xcodebuild -exportArchive -archivePath SampleApp.xcarchive -exportPath build -exportOptionsPlist SampleApp/ExportOptions.plist -allowProvisioningUpdates

      - name: Set up Git

        run: |

          git config --global user.name "tissa11223344"

          git config --global user.email "nilu.walmik@tissatech.com"

      - name: Create Release

        id: create_release

        uses: actions/create-release@v1

        with:

          tag_name: v1.3.1  # Replace with your desired tag name

          release_name: Release v1.3.1  # Replace with your desired release name

          draft: false

          prerelease: false

        env:

          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}

 

      - name: Upload IPA

        id: upload_ipa

        uses: actions/upload-release-asset@v1

        with:

          upload_url: ${{ steps.create_release.outputs.upload_url }}

          asset_path: build/SampleApp.ipa

          asset_name: SampleApp.ipa

          asset_content_type: application/octet-stream

        env:

          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}

